baseURL = '/'
languageCode = 'en-us'
title = 'UPCOMINGTRADER'
theme = "mainroad"
# paginate = "20"
paginate = "5"
# paginate = "3500"
googleAnalytics = "G-0FLS2ZJC44"
timeout = 60000
minify = true

disableKinds = ["taxonomy"]

[permalinks]
  posts = "/blog/:title/"

[Params]
  description = "upcomingtrader blog where upcoming traders come to learn how to become a successful trader."
  twitter_cards = true
  opengraph = true
  readmore = true
  authorbox = true
  post_meta = [ "author", "date" ]
  googleFontsLink = "https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
  pager = true
  dateformat = "Jan _2 2006"
  # customJS = ["js/analytics.js"]
  # customJS = ["js/search.js"]

[Params.thumbnail]
  visibility = ["list", "post"]

[Params.style.vars]
  highlightColor = "#FFCD6D" # Override highlight color
  backgroundColor = "#0E171B" # Override background color

  # backgroundColor = "#FFCD6D" # Override background color
  # highlightColor = "#37c0de" # Override highlight color
  # color: #3EC9E4; #sky blue
  # color: #FFCD6D;
  # color: #EAECEB;

  # Override font-family sets
  # Take care of different quotes OR escaping symbols in these params if necessary
  # fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
  # Secondary font-family set responsible for pre, code, kbd, and samp tags font
  # fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

  fontFamilyPrimary = "Poppins"
  fontFamilySecondary = "Georgia"

[Params.logo]
  image = "logo_round_1024x1024.png"
  title = "UPCOMINGTRADER"
  subtitle = "Learn to lose gracefully..."

[Author] # Used in authorbox
  link = "ut"
  name = "UPCOMINGTRADER"
  bio = "If you learn to lose gracefully, you too can learn how to trade like a professional."
  avatar = "logo_round_1024x1024.png"



[outputFormats.IndexJSON]
    mediaType = "application/json"
    baseName = "search"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "RSS", "JSON"]


[Params.widgets.search]
    [Params.widgets.search.input]
        name = "q"
        pre = "site:"

[[Params.widgets.social.custom]]
  title = "Youtube"
  url   = "https://www.youtube.com/@upcomingtradera/"
  icon  = "youtube.svg"

[[Params.widgets.social.custom]]
  title = "Pinterest"
  url   = "https://www.pinterest.com/upcomingtradera/"
  icon  = "pinterest.svg"

[[Params.widgets.social.custom]]
  title = "Mastodon"
  url   = "https://mastodon.social/@upcomingtradera"
  icon  = "mastodon.svg"

[[Params.widgets.social.custom]]
  title = "Reddit"
  url   = "https://www.reddit.com/user/upcomingtrader/"
  icon  = "reddit.svg"

[[Params.widgets.social.custom]]
  title = "Medium"
  url   = "https://upcomingtradera.medium.com/"
  icon  = "medium.svg"

[[Params.widgets.social.custom]]
  title = "Tumblr"
  url   = "https://www.tumblr.com/upcomingtradera/"
  icon  = "tumblr.svg"


[[Params.widgets.social.custom]]
  title = "Spotify"
  url   = "https://podcasters.spotify.com/pod/show/upcomingtradera"
  icon  = "spotify.svg"

[[Params.widgets.social.custom]]
  title = "Github"
  url   = "https://github.com/upcomingtradera"
  icon  = "github.svg"

[[Params.widgets.social.custom]]
  title = "TikTok"
  url   = "https://www.tiktok.com/@upcomingtradera"
  icon  = "tiktok.svg"


[Params.widgets.social]
  cached    = false # activate cache if true
  facebook  = "upcomingtradera"
  twitter   = "upcomingtradera"
  instagram = "upctrader"
  linkedin  = "upcomingtradera"

[Params.youtube]
  video_id = "wAps29x_njQ"

[Params.sidebar]
  # widgets = [ "search", "recent", "social" ]
  widgets = [ "youtube", "search", "recent" ]
  home   = "right"
  list   = "right"
  single = "right"


[[Menu.main]]
Name = "Home"
URL = "/"
weight = 1

[[Menu.main]]
name = "Blog"
url = "/blog/"
weight = 2

[[Menu.main]]
name = "About"
url = "/about/"
weight = 3

[[Menu.main]]
name = "Contact"
url = "/contact/"
weight = 4

[[Menu.main]]
name = "Privacy"
url = "/privacy/"
weight = 5


[[Menu.footer]]
Name = "Home"
URL = "/"
weight = 1

[[Menu.footer]]
name = "Blog"
url = "/blog/"
weight = 2

[[Menu.footer]]
name = "About"
url = "/about/"
weight = 3

[[Menu.footer]]
name = "Contact"
url = "/contact/"
weight = 4

[[Menu.footer]]
name = "Privacy"
url = "/privacy/"
weight = 5

