baseURL = '/'
languageCode = 'en-us'
title = 'UPCOMINGTRADER'
theme = "utheme"

[permalinks]
posts = "/blog/:title/"

[params]
mainPostFeatureImageWidth = 1024
mainPostFeatureImageHeight = 600
featureImageWidth = 1024
featureImageHeight = 700
topPostThumbnailImageWidth = 400
topPostThumbnailImageHeight = 400
recentPostsThumbnailImageWidth = 150
recentPostsThumbnailImageHeight = 150
trendingPostsMainThumbnailImageWidth = 250
trendingPostsMainThumbnailImageHeight = 250
trendingPostsSubThumbnailImageWidth = 1024
trendingPostsSubThumbnailImageHeight = 300
enableLeftSidebar = true
enableRightSidebar = true

featuredArticleHighlightedWord = 2

recentPostsCount  = 9
mainTrendingCount = 11
subTrendingCount  = 10

[taxonomies]
authors = ["UPCOMINGTRADER"]


[[Menu.main]]
Name = "Home"
URL = "/"
weight = 1

[[Menu.main]]
name = "Blog"
url = "/blog/"
weight = 2

[[Menu.main]]
name = "About"
url = "/about/"
weight = 3

[[Menu.main]]
name = "Contact"
url = "/contact/"
weight = 4

[[Menu.main]]
name = "Privacy"
url = "/privacy/"
weight = 5


[params.imageSizes]
large  = "1280x720 smart q85"
medium = "800x600  smart q70"
small  = "640x480  smart q55"

defaultArticle     = "defaultArticle"
defaultImageSize   = "900x900"

[params.imageSizes.featuredArticle]
large              = "1280x800"
medium             = "640x350"
small              = "320x175"

# large              = "1280x700"
# medium             = "640x350"
# small              = "320x175"

[params.imageSizes.recentArticles]
large              = "150x150"
medium             = "75x75"
small              = "50x50"

[params.imageSizes.topArticles]
large              = "300x300"
medium             = "150x150"
small              = "75x75"

[params.imageSizes.mainTrendingArticles]
large              = "1024x600"
medium             = "512x300"
small              = "256x150"

[params.imageSizes.subTrendingArticles]
large              = "1536x200"
medium             = "768x100"
small              = "384x50"


[params.imageSizes_V2]
# TVs
tv_large  = "3840x2160 smart q85"
tv_medium = "1920x1080 smart q75"

# Desktops
desktop_large  = "2560x1440 smart q85"
desktop_medium = "1920x1080 smart q75"
desktop_small  = "1366x768  smart q70"

# Laptops
laptop_large  = "1920x1080 smart q80"
laptop_medium = "1600x900  smart q75"
laptop_small  = "1366x768  smart q70"

# Tablets
tablet_landscape = "1366x1024 smart q75"
tablet_portrait  = "1024x768  smart q70"

# Mobile devices
mobile_landscape_large  = "1080x800 smart q65"
mobile_landscape_medium = "800x600  smart q60"
mobile_landscape_small  = "640x480  smart q55"
mobile_portrait_large   = "800x480  smart q65"
mobile_portrait_medium  = "640x360  smart q60"
mobile_portrait_small   = "480x320  smart q55"


[params.imageFormats]
# JPEG
jpg_tv_large   = "3840x2160 smart q85 format=jpg"
jpg_desktop    = "1920x1080 smart q75 format=jpg"
jpg_laptop     = "1600x900  smart q75 format=jpg"
jpg_tablet     = "1024x768  smart q70 format=jpg"
jpg_mobile     = "640x360  smart q65 format=jpg"

# WebP
webp_tv_large   = "3840x2160 smart q85 format=webp"
webp_desktop    = "1920x1080 smart q75 format=webp"
webp_laptop     = "1600x900  smart q75 format=webp"
webp_tablet     = "1024x768  smart q70 format=webp"
webp_mobile     = "640x360  smart q65 format=webp"

# AVIF
avif_tv_large   = "3840x2160 smart q85 format=avif"
avif_desktop    = "1920x1080 smart q75 format=avif"
avif_laptop     = "1600x900  smart q75 format=avif"
avif_tablet     = "1024x768  smart q70 format=avif"
avif_mobile     = "640x360  smart q65 format=avif"




[params.css]
header               = "css/header/header.css"
footer               = "css/footer/footer.css"
base                 = "css/baseStyle.css"
homepage             = "css/bodyContainer/bodyContainer.css"
featuredArticle      = "css/homepage/featuredArticle/featuredArticle.css"
mainTrendingArticles = "css/homepage/mainTrendingArticles/mainTrendingArticles.css"
subTrendingArticles  = "css/homepage/subTrendingArticles/subTrendingArticles.css"

topArticles          = "css/aside/leftSideBar/leftSideBar.css"
recentArticles       = "css/aside/rightSideBar/rightSideBar.css"



