#!/bin/bash

folders_to_delete=(
"accelerate-your-learning-curve-how-to-learn-trading-faster"
"banish-fear-from-trading-techniques-to-boost-confidence"
"becoming-a-smart-trader-tips-and-tricks"
"before-pivot-points-jesse-livermore-pivotal-point"
"choosing-the-best-timeframe-for-day-trading-a-guide-for-day-traders"
"conquering-trading-fears-a-psychological-perspective"
"danger-signals-associated-with-pivotal-points-a-traders-guide"
"danger-signals-in-trend-columns-jesse-livermores-pivot-point-system"
"day-trading-and-swing-trading-e-mini-nasdaq-futures-strategies-for-success"
"day-trading-and-swing-trading-strategies-in-the-e-mini-nasdaq-mastering-price-action-trading"
"day-trading-biases-navigating-the-psychological-terrain-of-futures-trading"
"day-trading-futures-strategies-for-mastering-futures-contracts"
"day-trading-in-the-futures-market-balancing-fear-greed-and-risk-psychology"
"day-trading-pitfalls-navigating-emotional-challenges-in-futures-strategy"
"day-trading-psychology-managing-risk-and-avoiding-burnout-in-the-futures-market"
"day-trading-simulator-the-essential-training-tool-for-aspiring-day-traders"
"day-trading-span-margin-futures-liquidity-strategy"
"day-trading-stress-navigating-emotions-in-the-futures-market"
"day-trading-swing-strategy-mastering-price-action-e-mini-nasdaq"
"decoding-the-1-2-3-strategy-in-trading"
"decoding-the-8-week-rule-in-trading"
"demystifying-the-5-3-1-rule-in-trading-a-beginners-guide"
"differentiating-primary-from-secondary-movements-in-jesse-livermores-pivotal-points-trading-system"
"elevating-futures-trading-the-synergy-of-lifelong-learning-and-community-engagement"
"e-mini-nasdaq-futures-price-action-mastery-for-day-trading-success"
"emotional-biases-in-day-trading-navigating-the-complex-world-of-futures-contracts"
"experience-the-trading-world-with-a-demo-futures-account"
"exploring-the-possibilities-of-1-minute-trading"
"facing-the-risks-the-maximum-daily-loss-in-trading-explained"
"facing-the-tough-reality-what-percentage-of-traders-eventually-give-up"
"facing-your-fears-tackling-the-biggest-challenges-in-trading"
"futures-contract-speculation-navigating-day-trading-amidst-market-volatility"
"futures-trading-e-mini-nasdaq-advanced-day-trading-price-action-strategies"
"futures-trading-simulator-the-essential-tool-for-every-trader"
"harnessing-day-trading-swing-trading-tactics-e-mini-nasdaq-futures-arena"
"how-many-people-achieve-success-in-day-trading"
"how-to-use-jesse-livermore-trading-method-for-sustained-futures-trading"
"identification-of-pivotal-points-unraveling-jesse-livermores-legacy-in-modern-trading"
"identifying-the-easiest-futures-to-trade-a-guide-for-beginners"
"influence-of-secondary-movements-on-trend-analysis-jesse-livermores-pivot-point-system"
"ink-color-significance-in-trend-columns-understanding-jesse-livermores-pivot-point-system"
"inspirational-jesse-livermore-trading-quotes"
"introduction-to-futures-trading-for-beginners-and-advanced-traders"
"introduction-to-secondary-movements-jesse-livermores-pivot-point-system"
"jesse-livermore-decoding-the-genius-of-an-early-technical-analysis-visionary"
"jesse-livermores-application-of-trend-columns-in-stock-technical-analysis"
"jesse-livermores-trend-columns-and-pivot-point-system"
"leveraging-the-80-20-trading-method-for-higher-returns"
"mastering-confidence-an-essential-trait-for-successful-trading"
"mastering-the-mindset-emotional-resilience-in-futures-trading"
"natural-movements-and-pivotal-points-jesse-livermores-pivot-point-system"
"natural-movements-and-secondary-columns-jesse-livermores-pivot-point-system"
"natural-movements-in-jesse-livermores-pivot-point-system"
"navigating-maximum-daily-losses-in-trading"
"navigating-the-market-with-pivotal-points-a-deep-dive-into-their-essence-and-significance"
"overcoming-the-fear-how-to-trade-confidently"
"pivotal-points-and-key-prices-navigating-the-markets-landmarks"
"pivotal-points-and-market-strength-a-deep-dive-into-their-relationship"
"pivotal-points-and-trend-analysis-gleaning-insights-from-jesse-livermores-market-mastery"
"pivotal-points-in-natural-rally-and-reaction-columns-a-deep-dive-into-market-dynamics"
"pivotal-points-in-technical-analysis-when-great-minds-converge-on-similar-realizations"
"pivotal-points-within-trend-columns-jesse-livermores-pivot-point-system"
"practical-application-of-pivotal-points-navigating-market-transitions"
"practical-implications-of-natural-movements-in-jesse-livermores-pivot-point-system"
"practical-implications-of-secondary-movements-in-jesse-livermores-pivot-point-system"
"practical-implications-of-trend-columns-in-jesse-livermores-pivot-point-system"
"safe-day-trading-navigating-futures-contracts-with-emotional-mastery"
"secondary-movements-and-market-strength-insights-from-jesse-livermores-pivot-point-system"
"secondary-movements-and-pivotal-points-in-jesse-livermores-pivot-point-system"
"secondary-movements-and-six-point-changes-jesse-livermores-pivot-point-system"
"significance-of-six-point-movements-delving-into-jesse-livermores-pivot-point-system"
"success-in-sight-what-percentage-of-traders-really-make-it"
"success-in-trading-a-look-at-successful-trader-statistics"
"swing-trading-e-mini-nasdaq-futures-contracts-comprehensive-day-trading-guide"
"the-best-5-minute-day-trading-strategy-a-comprehensive-guide"
"the-ink-and-pencil-dynamic-in-jesse-livermores-pivot-point-system"
"the-nuances-of-secondary-movements-in-stock-trading-jesse-livermores-pivot-point-system"
"timing-is-everything-choosing-the-best-timeframe-for-day-trading"
"trading-confidently-a-comprehensive-guide"
"transition-between-trend-columns-and-natural-columns-a-deep-dive-into-jesse-livermores-pivot-point-system"
"transitioning-to-natural-columns-a-deep-dive-into-jesse-livermores-pivot-point-system"
"transitioning-to-secondary-columns-in-jesse-livermores-pivotal-points-system"
"trend-analysis-using-natural-movements-jesse-livermores-pivot-point-system"
"trend-columns-and-price-movements-jesse-livermores-pivot-point-system"
"trend-resumption-indicators-jesse-livermores-pivot-point-system"
"understanding-futures-contracts-balancing-day-trading-risks-with-market-psychology"
"understanding-natural-movements-in-jesse-livermores-pivot-point-system"
"understanding-the-biggest-risks-of-loss-in-futures-trading"
"what-are-jesse-livermore-principles-in-trading"
"what-is-the-maximum-loss-permitted-in-a-day-of-trading"
"who-was-jesse-livermore-unraveling-the-enigmatic-mind-of-wall-streets-most-legendary-trader-and-his-enduring-legacy"
"why-do-i-always-lose-bets-breaking-down-the-betting-blues"
)

# Iterate through the array
for folder in "${folders_to_delete[@]}"; do
    # Check if the folder exists
    if [ -d "$folder" ]; then
        echo "Removing $folder..."
        rm -rf "$folder"
    else
        echo "Folder $folder does not exist."
    fi
done

